### ISSUE TITLE
Move TAG 2012 Articles From Knowledge Base To AidTransparency Website

### ISSUE THREAD

**Issue by wendyrogers** [IATI/AidTransparency-website#5]
Following a review by SF/JH and WR, All the articles that now remain in http://support.iatistandard.org/categories/20036606-TAG-Workshop-May-2012 now need to move to the TAG workshop area of the AidTransparency website

**Comment by hayfield** [comment]
The linked location no longer exists. Do the documents still need adding, or can this issue be closed?
