### ISSUE TITLE
Redirect https://www.aidtransparency.net/feed to https://iatistandard.org/en/feed/

### ISSUE THREAD

**Issue by andylolz** [IATI/AidTransparency-website#9]
This is dependent on IATI/preview-website#231.

**Comment by andylolz** [comment]
Sounds like there won’t be any redirects, and instead aidtransparency.net will just be switched off completely. So closing this.

**Comment by samuele-mattiuzzo** [comment]
All the urls that need redirecting have been mapped, so no need to raise an issue for each one.

**Comment by andylolz** [comment]
> no need to raise an issue for each one

Ha, I’ve no intention of doing that. On the contrary, I just closed this one.

In fact I only opened this (back in august) when I realised my feedreader had stopped showing recent news:

![screen shot 2018-10-17 at 12 53 17](https://user-images.githubusercontent.com/464193/47084547-af296900-d20b-11e8-9a1e-c46d5bb5820b.png)
